# TODO - centos images have updated maven versions (https://github.com/openshift/jenkins/commit/5dbd8cfda01f6943257ef3768c7cef03cc251e19#diff-ac27c71413104e2429bb19a0f306fe46)
# rhel images move to SCL (i.e. up to date) maven in OCP 3.6
FROM openshift/jenkins-slave-maven-centos7:latest
ADD settings.xml $HOME/.m2/settings.xml